[package]
name = "test-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
lambda_http = "0.13.0"

tokio = { version = "1", features = ["macros"] }
wasmtime = "25.0.1"
aws-config = { version= "1.5.10", features = ["behavior-version-latest"] }
aws-sdk-dynamodb = "1.54.0"
serde_json = "1.0.132"
serde = {version = "1.0.215", features = ["derive"]}
thiserror = "2.0.3"
reqwest = { version = "0.12.9", features = ["json", "rustls-tls"] }

[package.metadata.lambda.env]
CHECK_URL = "http://localhost:8000"
REMOTE_URL = "http://localhost:9001"
